export interface OrganicChemicalData {
  id: string;
  name: string;
  symbol: string; // The text to display in the bubble
  type: 'alkane' | 'alkene' | 'alkyne' | 'aromatic' | 'alcohol' | 'phenol' | 'aldehyde' | 'ketone' | 'carboxylic' | 'ester' | 'reagent' | 'catalyst';
  color: string;
  glowColor: string;
  textColor: string;
  shape: 'circle' | 'hexagon';
}

export const ORGANIC_CHEMICALS: Record<string, OrganicChemicalData> = {
  // --- TARGETS (Board) ---
  // Alkanes
  'CH4': { id: 'CH4', name: 'Methane', symbol: 'CH₄', type: 'alkane', color: '#334155', glowColor: '#475569', textColor: '#FFFFFF', shape: 'hexagon' },
  'C2H6': { id: 'C2H6', name: 'Ethane', symbol: 'C₂H₆', type: 'alkane', color: '#334155', glowColor: '#475569', textColor: '#FFFFFF', shape: 'hexagon' },
  // Alkenes
  'C2H4': { id: 'C2H4', name: 'Ethene', symbol: 'C₂H₄', type: 'alkene', color: '#1E40AF', glowColor: '#3B82F6', textColor: '#FFFFFF', shape: 'hexagon' },
  'C3H6': { id: 'C3H6', name: 'Propene', symbol: 'C₃H₆', type: 'alkene', color: '#1E40AF', glowColor: '#3B82F6', textColor: '#FFFFFF', shape: 'hexagon' },
  // Aromatics
  'C6H6': { id: 'C6H6', name: 'Benzene', symbol: 'C₆H₆', type: 'aromatic', color: '#5B21B6', glowColor: '#8B5CF6', textColor: '#FFFFFF', shape: 'hexagon' },
  'C6H5CH3': { id: 'C6H5CH3', name: 'Toluene', symbol: 'C₆H₅CH₃', type: 'aromatic', color: '#6D28D9', glowColor: '#A78BFA', textColor: '#FFFFFF', shape: 'hexagon' },

  // New Families
  'C6H5OH': { id: 'C6H5OH', name: 'Phenol', symbol: 'C₆H₅OH', type: 'phenol', color: '#991B1B', glowColor: '#EF4444', textColor: '#FFFFFF', shape: 'hexagon' },
  'C2H2': { id: 'C2H2', name: 'Acetylene', symbol: 'C₂H₂', type: 'alkyne', color: '#A16207', glowColor: '#EAB308', textColor: '#FFFFFF', shape: 'hexagon' },
  'C3H4': { id: 'C3H4', name: 'Propyne', symbol: 'C₃H₄', type: 'alkyne', color: '#A16207', glowColor: '#EAB308', textColor: '#FFFFFF', shape: 'hexagon' },
  'HCOOCH3': { id: 'HCOOCH3', name: 'Methyl Formate', symbol: 'HCOOCH₃', type: 'ester', color: '#047857', glowColor: '#10B981', textColor: '#FFFFFF', shape: 'hexagon' },
  'HCHO': { id: 'HCHO', name: 'Formaldehyde', symbol: 'HCHO', type: 'aldehyde', color: '#B45309', glowColor: '#F59E0B', textColor: '#FFFFFF', shape: 'hexagon' },
  'CH3CHO': { id: 'CH3CHO', name: 'Acetaldehyde', symbol: 'CH₃CHO', type: 'aldehyde', color: '#B45309', glowColor: '#F59E0B', textColor: '#FFFFFF', shape: 'hexagon' },
  // Alcohols
  'C2H5OH': { id: 'C2H5OH', name: 'Ethanol', symbol: 'C₂H₅OH', type: 'alcohol', color: '#0891B2', glowColor: '#22D3EE', textColor: '#FFFFFF', shape: 'hexagon' },
  // Halides (Generated by reaction or board)
  'C2H5Cl': { id: 'C2H5Cl', name: 'Chloroethane', symbol: 'C₂H₅Cl', type: 'alkane', color: '#065F46', glowColor: '#10B981', textColor: '#FFFFFF', shape: 'hexagon' },

  // Carboxylic Acids & Ketones
  'HCOOH': { id: 'HCOOH', name: 'Formic Acid', symbol: 'HCOOH', type: 'carboxylic', color: '#D97706', glowColor: '#F59E0B', textColor: '#FFFFFF', shape: 'hexagon' },
  'CH3COOH': { id: 'CH3COOH', name: 'Acetic Acid', symbol: 'CH₃COOH', type: 'carboxylic', color: '#D97706', glowColor: '#F59E0B', textColor: '#FFFFFF', shape: 'hexagon' },
  'CH3COCH3': { id: 'CH3COCH3', name: 'Acetone', symbol: 'CH₃COCH₃', type: 'ketone', color: '#BE185D', glowColor: '#EC4899', textColor: '#FFFFFF', shape: 'hexagon' },

  // --- REAGENTS (Shooter) ---
  'Na': { id: 'Na', name: 'Sodium', symbol: 'Na', type: 'reagent', color: '#9CA3AF', glowColor: '#D1D5DB', textColor: '#000000', shape: 'circle' },
  'Br2': { id: 'Br2', name: 'Bromine', symbol: 'Br₂', type: 'reagent', color: '#9A3412', glowColor: '#F97316', textColor: '#FFFFFF', shape: 'circle' },
  'Br2_Fe': { id: 'Br2_Fe', name: 'Br2 / Fe', symbol: 'Br₂, Fe', type: 'reagent', color: '#78350F', glowColor: '#B45309', textColor: '#FFFFFF', shape: 'circle' },
  'H2_Ni': { id: 'H2_Ni', name: 'H2 / Ni, t°', symbol: 'H₂+Ni', type: 'reagent', color: '#0F766E', glowColor: '#14B8A6', textColor: '#FFFFFF', shape: 'circle' },
  'Cl2_askt': { id: 'Cl2_askt', name: 'Cl2 / askt', symbol: 'Cl₂+hv', type: 'reagent', color: '#166534', glowColor: '#22C55E', textColor: '#FFFFFF', shape: 'circle' },
  'NaOH': { id: 'NaOH', name: 'NaOH', symbol: 'NaOH', type: 'reagent', color: '#BE185D', glowColor: '#F43F5E', textColor: '#FFFFFF', shape: 'circle' },
  'NaOH_t': { id: 'NaOH_t', name: 'NaOH / t°', symbol: 'NaOH, t°', type: 'reagent', color: '#C026D3', glowColor: '#E879F9', textColor: '#FFFFFF', shape: 'circle' },
  'KMnO4_t': { id: 'KMnO4_t', name: 'KMnO4 / t°', symbol: 'KMnO₄, t°', type: 'reagent', color: '#701A75', glowColor: '#D946EF', textColor: '#FFFFFF', shape: 'circle' },
  'CuO_t': { id: 'CuO_t', name: 'CuO / t°', symbol: 'CuO, t°', type: 'reagent', color: '#1E3A8A', glowColor: '#3B82F6', textColor: '#FFFFFF', shape: 'circle' },
  'AgNO3_NH3': { id: 'AgNO3_NH3', name: 'AgNO3 / NH3', symbol: 'AgNO₃/NH₃', type: 'reagent', color: '#475569', glowColor: '#94A3B8', textColor: '#FFFFFF', shape: 'circle' },
  'H2O_H': { id: 'H2O_H', name: 'H2O / H+', symbol: 'H₂O/H⁺', type: 'reagent', color: '#0EA5E9', glowColor: '#38BDF8', textColor: '#FFFFFF', shape: 'circle' },
  'HCl': { id: 'HCl', name: 'HCl', symbol: 'HCl', type: 'reagent', color: '#16A34A', glowColor: '#22C55E', textColor: '#FFFFFF', shape: 'circle' },
};
